"""Machine-dog strategy for CUMCM 2026 B (questions 3/4).

Run after starting the simulator:
    python q3_solver.py --robot-id 202609001179

The program deliberately keeps all observations in ``robot_log.jsonl`` so that
an unsuccessful rehearsal can be inspected and tuned without changing the
search logic.
"""
from __future__ import annotations

import argparse, json, math, time
from dataclasses import dataclass, asdict
from pathlib import Path
from urllib.request import Request, urlopen

DEG = math.pi / 180.0
R = 1800.0

@dataclass
class Observation:
    x: float; y: float; channel: int; result: str
    bearing: float | None = None
    virtual_time: float = 0.0

def norm(a: float) -> float:
    return a % 360.0

def point_on_ray(p, bearing, distance):
    a = bearing * DEG
    return (p[0] + distance * math.cos(a), p[1] + distance * math.sin(a))

def ray_intersection(p1, b1, p2, b2):
    """Intersection of two measured rays; returns None for near-parallel rays."""
    a, c = b1 * DEG, b2 * DEG
    u, v = (math.cos(a), math.sin(a)), (math.cos(c), math.sin(c))
    dx, dy = p2[0] - p1[0], p2[1] - p1[1]
    cross = u[0] * v[1] - u[1] * v[0]
    if abs(cross) < 0.15:  # angle below about 9 degrees is ill-conditioned
        return None
    t = (dx * v[1] - dy * v[0]) / cross
    s = (dx * u[1] - dy * u[0]) / cross
    q = (p1[0] + t * u[0], p1[1] + t * u[1])
    # Both rays are half-lines.  Accepting an intersection behind the
    # second detector creates plausible-looking but completely false fixes.
    if t < 0 or s < 0:
        return None
    return q

def robust_location(obs: list[Observation]):
    """Robustly combine all non-parallel bearing intersections.

    A single directional bearing is quantized/noisy.  Taking only the most
    recent two rays makes a clear attempt unnecessarily fragile, especially
    when the two viewpoints are nearly collinear with the jammer.
    """
    if len(obs) < 2:
        return None
    # Build the feasible intersection region of the +/-1 degree bearing
    # wedges (question 1), rather than intersecting only the noisy center
    # lines.  This removes the systematic bias of a single reading.
    feasible = []
    for i in range(len(obs)):
        for j in range(i + 1, len(obs)):
            for bi in (obs[i].bearing - 1.0, obs[i].bearing + 1.0):
                for bj in (obs[j].bearing - 1.0, obs[j].bearing + 1.0):
                    q = ray_intersection((obs[i].x, obs[i].y), bi,
                                         (obs[j].x, obs[j].y), bj)
                    if q and math.hypot(*q) <= R + 100:
                        ok = True
                        for o in obs:
                            a = norm(math.degrees(math.atan2(q[1]-o.y, q[0]-o.x)))
                            d = abs((a - o.bearing + 180) % 360 - 180)
                            if d > 1.25:
                                ok = False; break
                        if ok:
                            feasible.append(q)
    if feasible:
        return (sum(p[0] for p in feasible) / len(feasible),
                sum(p[1] for p in feasible) / len(feasible))

    # Fallback for sparse/noisy observations: use center-line intersections.
    pts = []
    for i in range(len(obs)):
        for j in range(i + 1, len(obs)):
            q = ray_intersection((obs[i].x, obs[i].y), obs[i].bearing,
                                 (obs[j].x, obs[j].y), obs[j].bearing)
            if q and math.hypot(*q) <= R + 300:
                pts.append(q)
    if not pts:
        return None
    # Keep the dense consensus cluster before taking a coordinate median.
    # This discards intersections generated by an occasional bad bearing.
    best = min(pts, key=lambda p: sum(math.hypot(p[0] - q[0], p[1] - q[1])
                                      for q in pts))
    close = [p for p in pts if math.hypot(p[0] - best[0], p[1] - best[1]) <= 220]
    xs = sorted(p[0] for p in close); ys = sorted(p[1] for p in close)
    return (xs[len(xs)//2], ys[len(ys)//2])

def clear_neighborhood(sim, loc, ch):
    """Clear at the estimate and a small cross around it for bearing error."""
    # A failed clear is cheap compared with leaving a jammer active.  The
    # offsets cover the typical final-position error without broad guessing.
    # The +/-1 degree bearing error can translate to tens of metres at the
    # edge of a 1--1.5 km receive radius.  Search concentric rings, ordered
    # by distance, instead of giving up after one inaccurate intersection.
    offsets = [(0, 0)]
    for radius in (20, 40, 60, 80):
        for k in range(8):
            a = k * math.pi / 4
            offsets.append((radius * math.cos(a), radius * math.sin(a)))
    for dx, dy in offsets:
        p = (loc[0] + dx, loc[1] + dy)
        if math.hypot(*p) > R:
            continue
        cr = sim.clear(p, ch)
        if cr.get('clear_result') == 'success':
            return True
    return False

def refine_location(obs, loc, span=100.0, step=10.0):
    """Local robust least-squares refinement of an intersection estimate."""
    best, best_cost = loc, float('inf')
    for ix in range(-int(span // step), int(span // step) + 1):
        for iy in range(-int(span // step), int(span // step) + 1):
            p = (loc[0] + ix * step, loc[1] + iy * step)
            if math.hypot(*p) > R:
                continue
            cost = 0.0
            for o in obs:
                a = norm(math.degrees(math.atan2(p[1] - o.y, p[0] - o.x)))
                d = abs((a - o.bearing + 180) % 360 - 180)
                # Huber-like angular loss limits the effect of bad readings.
                cost += d * d if d <= 1.5 else 1.5 * (2 * d - 1.5)
            if cost < best_cost:
                best, best_cost = p, cost
    return best

class Simulator:
    def __init__(self, base, robot_id, log_file):
        self.base, self.robot_id, self.n = base.rstrip('/'), robot_id, 0
        self.pos = (0.0, 0.0); self.channel = 1
        self.log = open(log_file, 'a', encoding='utf-8')

    def call(self, path, payload=None):
        self.n += 1
        body = {'arena_id': 'default', 'robot_id': self.robot_id,
                'request_id': f'auto-{self.n}'}
        if payload: body.update(payload)
        req = Request(self.base + path, data=json.dumps(body).encode(),
                      headers={'Content-Type': 'application/json'}, method='POST')
        with urlopen(req, timeout=10) as r:
            ans = json.loads(r.read().decode('utf-8'))
        self.log.write(json.dumps({'path': path, 'request': body, 'response': ans}, ensure_ascii=False) + '\n')
        self.log.flush()
        if ans.get('accepted') is not True:
            raise RuntimeError(f'{path} rejected: {ans}')
        return ans

    def enter(self): return self.call('/enter')
    def exit(self): return self.call('/exit')
    def measure(self, p, ch):
        ans = self.call('/measure', {'position': {'x': p[0], 'y': p[1]}, 'channel': int(ch)})
        self.pos, self.channel = p, int(ch)
        return ans
    def clear(self, p, ch):
        ans = self.call('/clear', {'position': {'x': p[0], 'y': p[1]}, 'channel': int(ch)})
        self.pos = p
        return ans

@dataclass
class Observation:
    x: float; y: float; channel: int; result: str
    bearing: float | None = None
    virtual_time: float = 0.0

def norm(a: float) -> float:
    return a % 360.0

def point_on_ray(p, bearing, distance):
    a = bearing * DEG
    return (p[0] + distance * math.cos(a), p[1] + distance * math.sin(a))

def ray_intersection(p1, b1, p2, b2):
    """Intersection of two measured rays; returns None for near-parallel rays."""
    a, c = b1 * DEG, b2 * DEG
    u, v = (math.cos(a), math.sin(a)), (math.cos(c), math.sin(c))
    dx, dy = p2[0] - p1[0], p2[1] - p1[1]
    cross = u[0] * v[1] - u[1] * v[0]
    if abs(cross) < 0.15:  # angle below about 9 degrees is ill-conditioned
        return None
    t = (dx * v[1] - dy * v[0]) / cross
    s = (dx * u[1] - dy * u[0]) / cross
    q = (p1[0] + t * u[0], p1[1] + t * u[1])
    # Both rays are half-lines.  Accepting an intersection behind the
    # second detector creates plausible-looking but completely false fixes.
    if t < 0 or s < 0:
        return None
    return q

def robust_location(obs: list[Observation]):
    """Robustly combine all non-parallel bearing intersections.

    A single directional bearing is quantized/noisy.  Taking only the most
    recent two rays makes a clear attempt unnecessarily fragile, especially
    when the two viewpoints are nearly collinear with the jammer.
    """
    if len(obs) < 2:
        return None
    # Build the feasible intersection region of the +/-1 degree bearing
    # wedges (question 1), rather than intersecting only the noisy center
    # lines.  This removes the systematic bias of a single reading.
    feasible = []
    for i in range(len(obs)):
        for j in range(i + 1, len(obs)):
            for bi in (obs[i].bearing - 1.0, obs[i].bearing + 1.0):
                for bj in (obs[j].bearing - 1.0, obs[j].bearing + 1.0):
                    q = ray_intersection((obs[i].x, obs[i].y), bi,
                                         (obs[j].x, obs[j].y), bj)
                    if q and math.hypot(*q) <= R + 100:
                        ok = True
                        for o in obs:
                            a = norm(math.degrees(math.atan2(q[1]-o.y, q[0]-o.x)))
                            d = abs((a - o.bearing + 180) % 360 - 180)
                            if d > 1.25:
                                ok = False; break
                        if ok:
                            feasible.append(q)
    if feasible:
        return (sum(p[0] for p in feasible) / len(feasible),
                sum(p[1] for p in feasible) / len(feasible))

    # Fallback for sparse/noisy observations: use center-line intersections.
    pts = []
    for i in range(len(obs)):
        for j in range(i + 1, len(obs)):
            q = ray_intersection((obs[i].x, obs[i].y), obs[i].bearing,
                                 (obs[j].x, obs[j].y), obs[j].bearing)
            if q and math.hypot(*q) <= R + 300:
                pts.append(q)
    if not pts:
        return None
    # Keep the dense consensus cluster before taking a coordinate median.
    # This discards intersections generated by an occasional bad bearing.
    best = min(pts, key=lambda p: sum(math.hypot(p[0] - q[0], p[1] - q[1])
                                      for q in pts))
    close = [p for p in pts if math.hypot(p[0] - best[0], p[1] - best[1]) <= 220]
    xs = sorted(p[0] for p in close); ys = sorted(p[1] for p in close)
    return (xs[len(xs)//2], ys[len(ys)//2])

def clear_neighborhood(sim, loc, ch):
    """Clear at the estimate and a small cross around it for bearing error."""
    # A failed clear is cheap compared with leaving a jammer active.  The
    # offsets cover the typical final-position error without broad guessing.
    # The +/-1 degree bearing error can translate to tens of metres at the
    # edge of a 1--1.5 km receive radius.  Search concentric rings, ordered
    # by distance, instead of giving up after one inaccurate intersection.
    offsets = [(0, 0)]
    for radius in (20, 40, 60, 80):
        for k in range(8):
            a = k * math.pi / 4
            offsets.append((radius * math.cos(a), radius * math.sin(a)))
    for dx, dy in offsets:
        p = (loc[0] + dx, loc[1] + dy)
        if math.hypot(*p) > R:
            continue
        cr = sim.clear(p, ch)
        if cr.get('clear_result') == 'success':
            return True
    return False

def refine_location(obs, loc, span=100.0, step=10.0):
    """Local robust least-squares refinement of an intersection estimate."""
    best, best_cost = loc, float('inf')
    for ix in range(-int(span // step), int(span // step) + 1):
        for iy in range(-int(span // step), int(span // step) + 1):
            p = (loc[0] + ix * step, loc[1] + iy * step)
            if math.hypot(*p) > R:
                continue
            cost = 0.0
            for o in obs:
                a = norm(math.degrees(math.atan2(p[1] - o.y, p[0] - o.x)))
                d = abs((a - o.bearing + 180) % 360 - 180)
                # Huber-like angular loss limits the effect of bad readings.
                cost += d * d if d <= 1.5 else 1.5 * (2 * d - 1.5)
            if cost < best_cost:
                best, best_cost = p, cost
    return best

class Simulator:
    def __init__(self, base, robot_id, log_file):
        self.base, self.robot_id, self.n = base.rstrip('/'), robot_id, 0
        self.pos = (0.0, 0.0); self.channel = 1
        self.log = open(log_file, 'a', encoding='utf-8')

    def call(self, path, payload=None):
        self.n += 1
        body = {'arena_id': 'default', 'robot_id': self.robot_id,
                'request_id': f'auto-{self.n}'}
        if payload: body.update(payload)
        req = Request(self.base + path, data=json.dumps(body).encode(),
                      headers={'Content-Type': 'application/json'}, method='POST')
        with urlopen(req, timeout=10) as r:
            ans = json.loads(r.read().decode('utf-8'))
        self.log.write(json.dumps({'path': path, 'request': body, 'response': ans}, ensure_ascii=False) + '\n')
        self.log.flush()
        if ans.get('accepted') is not True:
            raise RuntimeError(f'{path} rejected: {ans}')
        return ans

    def enter(self): return self.call('/enter')
    def exit(self): return self.call('/exit')
    def measure(self, p, ch):
        ans = self.call('/measure', {'position': {'x': p[0], 'y': p[1]}, 'channel': int(ch)})
        self.pos, self.channel = p, int(ch)
        return ans
    def clear(self, p, ch):
        ans = self.call('/clear', {'position': {'x': p[0], 'y': p[1]}, 'channel': int(ch)})
        self.pos = p
        return ans

DISCOVERY_RADIUS = 1123.0
STATUS_UNSEEN = 'unseen'
STATUS_DIRECTIONAL = 'directional'
STATUS_LOCATED = 'located'
STATUS_CLEARED = 'cleared'
STATUS_ABSENT = 'absent'


def seven_probe_points():
    points = [(0.0, 0.0)]
    for k in range(6):
        a = 2.0 * math.pi * k / 6.0
        points.append((DISCOVERY_RADIUS * math.cos(a),
                       DISCOVERY_RADIUS * math.sin(a)))
    return points


def angle_quality(obs, point):
    """Quality of a second viewpoint for the first bearing observation."""
    baseline = math.degrees(math.atan2(point[1] - obs.y, point[0] - obs.x))
    delta = abs((baseline - obs.bearing + 180.0) % 360.0 - 180.0)
    # 1 at 90 degrees, 0 at a collinear baseline.
    return abs(math.sin(delta * DEG))


def second_probe(sim, first, candidates, tested):
    scored = []
    for p in candidates:
        key = (round(p[0], 6), round(p[1], 6))
        if key in tested:
            continue
        distance = math.hypot(p[0] - sim.pos[0], p[1] - sim.pos[1])
        # Travel time is in seconds; the angle term rewards stable
        # intersections.  The constants are deliberately conservative.
        score = distance / 5.0 + 5.0 - 10.0 * angle_quality(first, p)
        scored.append((score, p))
    return min(scored, default=(None, None))[1]


def run(sim):
    """Seven discovery stations with a shared dynamic task queue."""
    probes = seven_probe_points()
    state = {ch: {'status': STATUS_UNSEEN, 'obs': [], 'tested': set(),
                  'estimate': None, 'failed_obs_count': -1,
                  'retry_level': 0}
             for ch in range(1, 21)}
    active = set(state)
    unvisited = set(range(len(probes)))
    pending_second = set()
    clear_queue = []
    actions = 0
    max_actions = 1000

    def key(p):
        return (round(p[0], 6), round(p[1], 6))

    def second_candidates(ch):
        st = state[ch]
        result = list(probes)
        # Generate side-looking points from every observed bearing. If the
        # first two rays are noisy or nearly parallel, later observations can
        # still supply a well-conditioned baseline.
        for obs in st['obs']:
            a = obs.bearing * DEG
            for length in (250.0, 400.0, 600.0, 800.0, 1000.0, 1200.0):
                for side in (-1.0, 1.0):
                    q = (obs.x - side * length * math.sin(a),
                         obs.y + side * length * math.cos(a))
                    if math.hypot(*q) <= R:
                        result.append(q)
            # Local rings keep the second point inside the source's receive
            # disk when the first observation was near its 1000 m boundary.
            for radius in (300.0, 600.0, 900.0):
                for k in range(12):
                    t = 2.0 * math.pi * k / 12.0
                    q = (obs.x + radius * math.cos(t),
                         obs.y + radius * math.sin(t))
                    if math.hypot(*q) <= R:
                        result.append(q)
        return [p for p in result if key(p) not in st['tested']]

    def enqueue_estimates():
        for ch in list(active):
            st = state[ch]
            if len(st['obs']) < 2 or len(st['obs']) <= st['failed_obs_count']:
                continue
            if st['status'] != STATUS_DIRECTIONAL:
                continue
            loc = robust_location(st['obs'][-10:])
            if loc is None or math.hypot(*loc) > R + 20:
                continue
            st['estimate'] = refine_location(st['obs'][-10:], loc)
            st['status'] = STATUS_LOCATED
            if not any(item[0] == ch for item in clear_queue):
                clear_queue.append((ch, st['estimate'], len(st['obs'])))

    def execute_clear(item):
        ch, loc, obs_count = item
        if ch not in active:
            return
        if clear_neighborhood(sim, loc, ch):
            state[ch]['status'] = STATUS_CLEARED
            active.remove(ch)
            pending_second.discard(ch)
            return
        # A failed clear invalidates this estimate. Keep the channel pending
        # and require a new bearing before trying another clear.
        st = state[ch]
        st['status'] = STATUS_DIRECTIONAL
        st['estimate'] = None
        st['failed_obs_count'] = obs_count
        st['retry_level'] += 1
        st['tested'].clear()
        pending_second.add(ch)

    def task_candidates():
        candidates = []
        for item in clear_queue:
            ch, loc, _ = item
            d = math.hypot(loc[0] - sim.pos[0], loc[1] - sim.pos[1])
            candidates.append((d / 5.0 + 5.0 - 15.0, 'clear', item))
        for ch in sorted(pending_second):
            if ch not in active or not state[ch]['obs']:
                continue
            qs = second_candidates(ch)
            if not qs:
                continue
            # Pick the best candidate for this channel, but let it compete
            # globally with discovery and other channels.
            first = state[ch]['obs'][0]
            q = min(qs, key=lambda p: math.hypot(p[0] - sim.pos[0], p[1] - sim.pos[1])
                    - 900.0 * angle_quality(first, p))
            d = math.hypot(q[0] - sim.pos[0], q[1] - sim.pos[1])
            quality = angle_quality(first, q)
            candidates.append((d / 5.0 + 6.0 - 10.0 * quality,
                               'second', (ch, q)))
        if unvisited:
            for idx in unvisited:
                p = probes[idx]
                d = math.hypot(p[0] - sim.pos[0], p[1] - sim.pos[1])
                need = sum(len(state[ch]['obs']) == 0 for ch in active)
                candidates.append((d / 5.0 + 5.0 * max(1, need) - 4.0 * need,
                                   'discover', idx))
        return candidates

    def finish_directional(max_actions=260):
        """Use the remaining action budget to drain directional channels."""
        exhausted = set()
        recovery_counts = {ch: 0 for ch in active}
        max_channel_attempts = 12
        for _ in range(max_actions):
            enqueue_estimates()
            if clear_queue:
                item = min(clear_queue,
                           key=lambda x: math.hypot(x[1][0] - sim.pos[0],
                                                    x[1][1] - sim.pos[1]))
                clear_queue.remove(item)
                ch = item[0]
                execute_clear(item)
                # A failed clear resets tested, so this channel can be
                # retried in the recovery pass.
                exhausted.discard(ch)
                recovery_counts[ch] = 0
                continue
            pending = [ch for ch in sorted(active)
                       if state[ch]['status'] == STATUS_DIRECTIONAL
                       and ch not in exhausted]
            if not pending:
                return
            # Prefer channels with only one bearing, then channels whose
            # estimate could not be cleared and need a fresh bearing.
            ch = min(pending, key=lambda c: len(state[c]['obs']))
            st = state[ch]
            if recovery_counts.get(ch, 0) >= max_channel_attempts:
                exhausted.add(ch)
                continue
            qs = second_candidates(ch)
            if not qs:
                exhausted.add(ch)
                continue
            first = st['obs'][0]
            p = min(qs, key=lambda q: (
                math.hypot(q[0] - sim.pos[0], q[1] - sim.pos[1])
                - 900.0 * angle_quality(first, q)))
            ans = sim.measure(p, ch)
            recovery_counts[ch] = recovery_counts.get(ch, 0) + 1
            st['tested'].add(key(p))
            result = ans.get('measure_result')
            if result == 'direction':
                st['obs'].append(Observation(p[0], p[1], ch, result,
                                             float(ans['svd_deg']),
                                             ans.get('virtual_time_s', 0)))
                st['status'] = STATUS_DIRECTIONAL
            elif result == 'near':
                st['status'] = STATUS_LOCATED
                pending_second.discard(ch)
                clear_queue.append((ch, p, len(st['obs'])))
            # no_signal consumes this candidate; after all candidates are
            # exhausted, this channel is left untouched rather than looping
            # over the same measurements.
        enqueue_estimates()
        while clear_queue:
            item = clear_queue.pop(0)
            execute_clear(item)

    while actions < max_actions:
        enqueue_estimates()
        candidates = task_candidates()
        if not candidates:
            break
        _, kind, payload = min(candidates, key=lambda x: x[0])
        actions += 1
        if kind == 'clear':
            clear_queue.remove(payload)
            execute_clear(payload)
            continue
        if kind == 'second':
            ch, p = payload
            st = state[ch]
            ans = sim.measure(p, ch)
            st['tested'].add(key(p))
            result = ans.get('measure_result')
            if result == 'direction':
                st['obs'].append(Observation(p[0], p[1], ch, result,
                                             float(ans['svd_deg']),
                                             ans.get('virtual_time_s', 0)))
                st['status'] = STATUS_DIRECTIONAL
                # Do not remove the channel until the new bearings actually
                # yield a valid in-arena intersection. This prevents a
                # channel from ending in the misleading "閺堝鏌熼崥? state.
                pending_second.add(ch)
                enqueue_estimates()
                if st['status'] == STATUS_LOCATED:
                    pending_second.discard(ch)
            elif result == 'near':
                st['status'] = STATUS_LOCATED
                pending_second.discard(ch)
                clear_queue.append((ch, p, len(st['obs'])))
            continue

        idx = payload
        p = probes[idx]
        unvisited.remove(idx)
        # Discovery stations only measure channels with no bearing yet.
        for ch in sorted(active):
            st = state[ch]
            if st['obs']:
                continue
            ans = sim.measure(p, ch)
            st['tested'].add(key(p))
            result = ans.get('measure_result')
            if result == 'direction':
                st['status'] = STATUS_DIRECTIONAL
                st['obs'].append(Observation(p[0], p[1], ch, result,
                                             float(ans['svd_deg']),
                                             ans.get('virtual_time_s', 0)))
                pending_second.add(ch)
            elif result == 'near':
                st['status'] = STATUS_LOCATED
                clear_queue.append((ch, p, 0))
            else:
                st['status'] = STATUS_ABSENT
    finish_directional()
    enqueue_estimates()
    # A final localization pass is required because the last action may have
    # produced the second bearing immediately before the action budget ended.
    for ch in list(active):
        st = state[ch]
        if st['status'] == STATUS_DIRECTIONAL:
            loc = robust_location(st['obs'][-10:])
            if loc is not None and math.hypot(*loc) <= R + 20:
                st['estimate'] = refine_location(st['obs'][-10:], loc)
                st['status'] = STATUS_LOCATED
                clear_queue.append((ch, st['estimate'], len(st['obs'])))
    while clear_queue:
        item = clear_queue.pop(0)
        execute_clear(item)
    # A failed final clear reopens the channel for one bounded recovery pass.
    finish_directional(max_actions=120)
    return state


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--robot-id', required=True)
    ap.add_argument('--base', default='http://127.0.0.1:2026')
    ap.add_argument('--log', default='robot_log_q3_seven.jsonl')
    args = ap.parse_args()
    sim = Simulator(args.base, args.robot_id, args.log)
    sim.enter()
    state = run(sim)
    sim.exit()
    sim.log.close()
    cleared = sorted(ch for ch, st in state.items() if st['status'] == STATUS_CLEARED)
    print(json.dumps({'cleared_channels': cleared, 'count': len(cleared),
                      'states': {str(ch): st['status'] for ch, st in state.items()}},
                     ensure_ascii=False))


if __name__ == '__main__':
    main()

