"""Machine-dog strategy for CUMCM 2026 B (questions 3/4).

Run after starting the simulator:
    python robot_solver.py --robot-id 202609001179 --mode q4

The program deliberately keeps all observations in ``robot_log.jsonl`` so that
an unsuccessful rehearsal can be inspected and tuned without changing the
search logic.
"""
from __future__ import annotations

import argparse, json, math, time
from dataclasses import dataclass, asdict
from pathlib import Path
from urllib.request import Request, urlopen

DEG = math.pi / 180.0
R = 1800.0

@dataclass
class Observation:
    x: float; y: float; channel: int; result: str
    bearing: float | None = None
    virtual_time: float = 0.0

def norm(a: float) -> float:
    return a % 360.0

def point_on_ray(p, bearing, distance):
    a = bearing * DEG
    return (p[0] + distance * math.cos(a), p[1] + distance * math.sin(a))

def ray_intersection(p1, b1, p2, b2):
    """Intersection of two measured rays; returns None for near-parallel rays."""
    a, c = b1 * DEG, b2 * DEG
    u, v = (math.cos(a), math.sin(a)), (math.cos(c), math.sin(c))
    dx, dy = p2[0] - p1[0], p2[1] - p1[1]
    cross = u[0] * v[1] - u[1] * v[0]
    if abs(cross) < 0.15:  # angle below about 9 degrees is ill-conditioned
        return None
    t = (dx * v[1] - dy * v[0]) / cross
    s = (dx * u[1] - dy * u[0]) / cross
    q = (p1[0] + t * u[0], p1[1] + t * u[1])
    # Both rays are half-lines.  Accepting an intersection behind the
    # second detector creates plausible-looking but completely false fixes.
    if t < 0 or s < 0:
        return None
    return q

def robust_location(obs: list[Observation]):
    """Robustly combine all non-parallel bearing intersections.

    A single directional bearing is quantized/noisy.  Taking only the most
    recent two rays makes a clear attempt unnecessarily fragile, especially
    when the two viewpoints are nearly collinear with the jammer.
    """
    if len(obs) < 2:
        return None
    # Build the feasible intersection region of the +/-1 degree bearing
    # wedges (question 1), rather than intersecting only the noisy center
    # lines.  This removes the systematic bias of a single reading.
    feasible = []
    for i in range(len(obs)):
        for j in range(i + 1, len(obs)):
            for bi in (obs[i].bearing - 1.0, obs[i].bearing + 1.0):
                for bj in (obs[j].bearing - 1.0, obs[j].bearing + 1.0):
                    q = ray_intersection((obs[i].x, obs[i].y), bi,
                                         (obs[j].x, obs[j].y), bj)
                    if q and math.hypot(*q) <= R + 100:
                        ok = True
                        for o in obs:
                            a = norm(math.degrees(math.atan2(q[1]-o.y, q[0]-o.x)))
                            d = abs((a - o.bearing + 180) % 360 - 180)
                            if d > 1.25:
                                ok = False; break
                        if ok:
                            feasible.append(q)
    if feasible:
        return (sum(p[0] for p in feasible) / len(feasible),
                sum(p[1] for p in feasible) / len(feasible))

    # Fallback for sparse/noisy observations: use center-line intersections.
    pts = []
    for i in range(len(obs)):
        for j in range(i + 1, len(obs)):
            q = ray_intersection((obs[i].x, obs[i].y), obs[i].bearing,
                                 (obs[j].x, obs[j].y), obs[j].bearing)
            if q and math.hypot(*q) <= R + 300:
                pts.append(q)
    if not pts:
        return None
    # Keep the dense consensus cluster before taking a coordinate median.
    # This discards intersections generated by an occasional bad bearing.
    best = min(pts, key=lambda p: sum(math.hypot(p[0] - q[0], p[1] - q[1])
                                      for q in pts))
    close = [p for p in pts if math.hypot(p[0] - best[0], p[1] - best[1]) <= 220]
    xs = sorted(p[0] for p in close); ys = sorted(p[1] for p in close)
    return (xs[len(xs)//2], ys[len(ys)//2])

def clear_neighborhood(sim, loc, ch):
    """Clear at the estimate and a small cross around it for bearing error."""
    # A failed clear is cheap compared with leaving a jammer active.  The
    # offsets cover the typical final-position error without broad guessing.
    # The +/-1 degree bearing error can translate to tens of metres at the
    # edge of a 1--1.5 km receive radius.  Search concentric rings, ordered
    # by distance, instead of giving up after one inaccurate intersection.
    offsets = [(0, 0)]
    for radius in (20, 40, 60, 80):
        for k in range(8):
            a = k * math.pi / 4
            offsets.append((radius * math.cos(a), radius * math.sin(a)))
    for dx, dy in offsets:
        p = (loc[0] + dx, loc[1] + dy)
        if math.hypot(*p) > R:
            continue
        cr = sim.clear(p, ch)
        if cr.get('clear_result') == 'success':
            return True
    return False

def refine_location(obs, loc, span=100.0, step=10.0):
    """Local robust least-squares refinement of an intersection estimate."""
    best, best_cost = loc, float('inf')
    for ix in range(-int(span // step), int(span // step) + 1):
        for iy in range(-int(span // step), int(span // step) + 1):
            p = (loc[0] + ix * step, loc[1] + iy * step)
            if math.hypot(*p) > R:
                continue
            cost = 0.0
            for o in obs:
                a = norm(math.degrees(math.atan2(p[1] - o.y, p[0] - o.x)))
                d = abs((a - o.bearing + 180) % 360 - 180)
                # Huber-like angular loss limits the effect of bad readings.
                cost += d * d if d <= 1.5 else 1.5 * (2 * d - 1.5)
            if cost < best_cost:
                best, best_cost = p, cost
    return best

class Simulator:
    def __init__(self, base, robot_id, log_file):
        self.base, self.robot_id, self.n = base.rstrip('/'), robot_id, 0
        self.pos = (0.0, 0.0); self.channel = 1
        self.log = open(log_file, 'a', encoding='utf-8')

    def call(self, path, payload=None):
        self.n += 1
        body = {'arena_id': 'default', 'robot_id': self.robot_id,
                'request_id': f'auto-{self.n}'}
        if payload: body.update(payload)
        req = Request(self.base + path, data=json.dumps(body).encode(),
                      headers={'Content-Type': 'application/json'}, method='POST')
        with urlopen(req, timeout=10) as r:
            ans = json.loads(r.read().decode('utf-8'))
        self.log.write(json.dumps({'path': path, 'request': body, 'response': ans}, ensure_ascii=False) + '\n')
        self.log.flush()
        if ans.get('accepted') is not True:
            raise RuntimeError(f'{path} rejected: {ans}')
        return ans

    def enter(self): return self.call('/enter')
    def exit(self): return self.call('/exit')
    def measure(self, p, ch):
        ans = self.call('/measure', {'position': {'x': p[0], 'y': p[1]}, 'channel': int(ch)})
        self.pos, self.channel = p, int(ch)
        return ans
    def clear(self, p, ch):
        ans = self.call('/clear', {'position': {'x': p[0], 'y': p[1]}, 'channel': int(ch)})
        self.pos = p
        return ans

def grid_points(step=900):
    pts = []
    n = int(R / step) + 1
    for iy, y in enumerate(range(-int(R), int(R) + 1, step)):
        row = [x for x in range(-int(R), int(R) + 1, step) if x*x + y*y <= R*R]
        if iy % 2: row.reverse()
        pts += [(float(x), float(y)) for x in row]
    # include origin first only if it is not already in the grid
    return [(0.0, 0.0)] + [p for p in pts if p != (0.0, 0.0)]

def q4_scan_points():
    """Probe stations for three-point convex-hull discovery coverage."""
    # A 22-station layout covers the complete closed arena, including its
    # boundary: one central station, seven stations on a 1,000 m ring, and
    # fourteen stations on a 1,850 m ring just outside the arena.  The outer
    # ring is intentional: it handles a jammer on the boundary whose 180°
    # radiation sector points outward.
    pts = [(0.0, 0.0)]
    for radius, count, phase in ((1000.0, 7, 0.0),
                                 (1850.0, 14, 0.0)):
        for k in range(count):
            a = (phase + 360.0 * k / count) * DEG
            pts.append((radius * math.cos(a), radius * math.sin(a)))
    return pts


_q4_coverage_requirements = None
_q4_coverage_cache = {}
_q4_certified_sets = []


def q4_three_cover_certified(no_signal_indices):
    """Check the sampled arena for a three-point no-signal certificate.

    For each possible source sample, the measured no-signal stations within
    1000 m must surround it in angle.  This is equivalent to the source being
    in their convex hull, and rules out a hidden 180-degree source.  The test
    is deliberately conservative: if a sample is not covered, the channel is
    measured again at later stations.
    """
    global _q4_coverage_requirements
    key = tuple(sorted(no_signal_indices))
    if key in _q4_coverage_cache:
        return _q4_coverage_cache[key]
    selected = frozenset(key)
    # Coverage is monotone: adding no-signal stations cannot invalidate a
    # certificate that already passed.  Reuse a certified subset instead of
    # scanning the complete arena grid again.
    if any(certified <= selected for certified in _q4_certified_sets):
        _q4_coverage_cache[key] = True
        return True
    if len(key) < 3:
        _q4_coverage_cache[key] = False
        return False
    probes = q4_scan_points()
    if _q4_coverage_requirements is None:
        req = []
        # Check the complete closed arena, including its boundary.  The
        # outside ring in q4_scan_points makes this finite-grid certificate
        # meaningful even for outward-pointing sources on the boundary.
        for x in range(-1800, 1801, 40):
            for y in range(-1800, 1801, 40):
                if x * x + y * y > R * R:
                    continue
                candidates = []
                for i, p in enumerate(probes):
                    dx, dy = p[0] - x, p[1] - y
                    if dx * dx + dy * dy <= 1000.0 * 1000.0 + 1e-6:
                        candidates.append((i, math.atan2(dy, dx)))
                req.append((x, y, candidates))
        _q4_coverage_requirements = req
    selected = set(key)
    for x, y, candidates in _q4_coverage_requirements:
        angles = [a for i, a in candidates if i in selected]
        if len(angles) < 3:
            _q4_coverage_cache[key] = False
            return False
        angles.sort()
        max_gap = max(angles[j + 1] - angles[j]
                      for j in range(len(angles) - 1))
        max_gap = max(max_gap, angles[0] + 2.0 * math.pi - angles[-1])
        if max_gap > math.pi + 1e-9:
            _q4_coverage_cache[key] = False
            return False
    _q4_coverage_cache[key] = True
    _q4_certified_sets.append(frozenset(key))
    return True

def q3_probe_points():
    """Thirteen fixed probe stations for question 3.

    Eleven stations are on a radius-1300 ring.  Two non-coincident inner
    stations make the central part doubly covered while providing two
    geometrically distinct bearings.  The layout is checked against the
    radius-1800 arena on a fine grid before use in experiments.
    """
    pts = [(0.0, 0.0), (300.0, 0.0)]
    radius = 1300.0
    for k in range(11):
        a = 2.0 * math.pi * k / 11.0
        pts.append((radius * math.cos(a), radius * math.sin(a)))
    return pts


def _circle_intersections(c1, r1, c2, r2):
    """Return intersections of two circles (empty when they do not meet)."""
    dx, dy = c2[0] - c1[0], c2[1] - c1[1]
    d2 = dx * dx + dy * dy
    if d2 <= 1e-12:
        return []
    d = math.sqrt(d2)
    if d > r1 + r2 + 1e-9 or d < abs(r1 - r2) - 1e-9:
        return []
    a = (r1 * r1 - r2 * r2 + d2) / (2.0 * d)
    h2 = max(0.0, r1 * r1 - a * a)
    h = math.sqrt(h2)
    ux, uy = dx / d, dy / d
    px, py = c1[0] + a * ux, c1[1] + a * uy
    if h <= 1e-8:
        return [(px, py)]
    return [(px - h * uy, py + h * ux),
            (px + h * uy, py - h * ux)]


def _bisector_circle_intersections(c1, c2, boundary_center, boundary_radius):
    """Intersect a Voronoi bisector with a boundary circle."""
    nx, ny = c2[0] - c1[0], c2[1] - c1[1]
    nn = nx * nx + ny * ny
    if nn <= 1e-12:
        return []
    # |x-c1|^2 = |x-c2|^2  ->  n.x = k
    k = (c2[0] * c2[0] + c2[1] * c2[1]
         - c1[0] * c1[0] - c1[1] * c1[1]) / 2.0
    delta = (k - nx * boundary_center[0] - ny * boundary_center[1]) / nn
    fx = boundary_center[0] + nx * delta
    fy = boundary_center[1] + ny * delta
    h2 = boundary_radius * boundary_radius - ((fx - boundary_center[0]) ** 2
                                                + (fy - boundary_center[1]) ** 2)
    if h2 < -1e-7:
        return []
    h = math.sqrt(max(0.0, h2)) / math.sqrt(nn)
    return [(fx - ny * h, fy + nx * h),
            (fx + ny * h, fy - nx * h)] if h > 1e-8 else [(fx, fy)]


def _circumcenter(a, b, c):
    d = 2.0 * (a[0] * (b[1] - c[1]) + b[0] * (c[1] - a[1])
               + c[0] * (a[1] - b[1]))
    if abs(d) <= 1e-9:
        return None
    aa, bb, cc = a[0] ** 2 + a[1] ** 2, b[0] ** 2 + b[1] ** 2, c[0] ** 2 + c[1] ** 2
    return ((aa * (b[1] - c[1]) + bb * (c[1] - a[1])
             + cc * (a[1] - b[1])) / d,
            (aa * (c[0] - b[0]) + bb * (a[0] - c[0])
             + cc * (b[0] - a[0])) / d)


def disk_covered_by_union(center, disks, radius=1000.0,
                          domain_radius=R):
    """Conservatively test whether a probe disk adds no source locations.

    The maximum distance to the nearest previous detector is attained at a
    Voronoi vertex or on a boundary arc.  Checking those finite candidates
    avoids a coarse grid that could incorrectly discard a real source.
    The arena boundary is included because sources cannot lie outside it.
    """
    if not disks:
        return False
    domain_center = (0.0, 0.0)
    candidates = [center, domain_center]
    boundaries = [(center, radius), (domain_center, domain_radius)]

    for bc, br in boundaries:
        for disk in disks:
            candidates.extend(_circle_intersections(bc, br, disk, radius))
            d = math.hypot(disk[0] - bc[0], disk[1] - bc[1])
            if d > 1e-9:
                a = math.atan2(disk[1] - bc[1], disk[0] - bc[0])
                candidates.extend((
                    (bc[0] + br * math.cos(a), bc[1] + br * math.sin(a)),
                    (bc[0] - br * math.cos(a), bc[1] - br * math.sin(a))))
        for i in range(len(disks)):
            for j in range(i + 1, len(disks)):
                candidates.extend(_bisector_circle_intersections(
                    disks[i], disks[j], bc, br))

    for i in range(len(disks)):
        for j in range(i + 1, len(disks)):
            candidates.extend(_circle_intersections(disks[i], radius,
                                                    disks[j], radius))
    for i in range(len(disks)):
        for j in range(i + 1, len(disks)):
            for k in range(j + 1, len(disks)):
                q = _circumcenter(disks[i], disks[j], disks[k])
                if q is not None:
                    candidates.append(q)

    tol = 1e-6
    for q in candidates:
        if math.hypot(q[0] - center[0], q[1] - center[1]) > radius + tol:
            continue
        if math.hypot(*q) > domain_radius + tol:
            continue
        nearest = min(math.hypot(q[0] - p[0], q[1] - p[1]) for p in disks)
        if nearest > radius + tol:
            return False
    return True

def run_q3_online(sim):
    """Adaptive q3 policy with information-aware probe selection."""
    probes = q3_probe_points()
    unvisited = set(range(len(probes)))
    state = {
        ch: {'status': '未发现', 'obs': [], 'tested': set(),
             'estimate': None, 'queued_obs_count': -1,
             'blocked_obs_count': -1}
        for ch in range(1, 21)
    }
    active = set(state)
    clear_queue = []

    def enqueue_estimates():
        for ch in list(active):
            st = state[ch]
            if len(st['obs']) < 2 or len(st['obs']) <= st['blocked_obs_count']:
                continue
            if st['status'] not in ('有方向', '已定位'):
                continue
            loc = robust_location(st['obs'][-10:])
            if loc is None or math.hypot(*loc) > R + 20:
                continue
            loc = refine_location(st['obs'][-10:], loc)
            st['estimate'] = loc
            st['status'] = '已定位'
            if st['queued_obs_count'] < len(st['obs']):
                clear_queue.append((ch, loc, len(st['obs'])))
                st['queued_obs_count'] = len(st['obs'])

    def clear_one(item):
        ch, loc, obs_count = item
        if ch not in active:
            return
        if clear_neighborhood(sim, loc, ch):
            state[ch]['status'] = '已清除'
            active.remove(ch)
            return
        # Do not retry the same estimate. A new direction observation is
        # required before this channel can re-enter the clear queue.
        state[ch]['status'] = '有方向'
        state[ch]['estimate'] = None
        state[ch]['blocked_obs_count'] = obs_count
        clear_queue[:] = [item for item in clear_queue if item[0] != ch]
        # Permit a fresh pass over probe stations. Without resetting this set,
        # a failed two-bearing estimate could leave the channel stranded when
        # all stations had already been visited once.
        state[ch]['tested'].clear()

    def probe_gain(idx):
        """Expected information gain of visiting a probe."""
        p = probes[idx]
        gain = 0.0
        for ch in active:
            st = state[ch]
            nobs = len(st['obs'])
            if nobs >= 2:
                continue
            if nobs == 0:
                gain += 1.0
            else:
                # Prefer a baseline transverse to the first bearing; this
                # makes the second ray well-conditioned.
                o = st['obs'][0]
                baseline = math.degrees(math.atan2(p[1] - o.y, p[0] - o.x))
                diff = abs((baseline - o.bearing + 180.0) % 360.0 - 180.0)
                gain += 0.5 + 2.0 * abs(math.sin(diff * DEG))
        return gain

    while True:
        enqueue_estimates()
        # Compare every available action instead of always clearing or always
        # taking the nearest probe. The negative information term rewards a
        # probe that can discover channels or complete a triangulation.
        candidates = []
        for item in clear_queue:
            ch, loc, _ = item
            d = math.hypot(loc[0] - sim.pos[0], loc[1] - sim.pos[1])
            candidates.append((d / 5.0 + 5.0 - 12.0, 'clear', item))
        probe_indices = set(unvisited)
        # A first bearing may be obtained at the last new station. Revisit
        # stations that have not yet been tested for a single-bearing channel
        # so every source gets a genuine second view.
        for ch in active:
            st = state[ch]
            retry = st['blocked_obs_count'] >= 0 and len(st['obs']) <= st['blocked_obs_count']
            if len(st['obs']) == 1 or retry:
                probe_indices.update(i for i in range(len(probes))
                                     if i not in st['tested'])
        for idx in probe_indices:
            p = probes[idx]
            d = math.hypot(p[0] - sim.pos[0], p[1] - sim.pos[1])
            pending = sum(len(state[ch]['obs']) < 2 for ch in active)
            revisit = idx not in unvisited
            cost = d / 5.0 + 5.0 * max(1, pending) - 8.0 * probe_gain(idx)
            if revisit:
                cost -= 4.0
            candidates.append((cost, 'probe', idx))
        if not candidates:
            break
        _, kind, payload = min(candidates, key=lambda x: x[0])
        if kind == 'clear':
            clear_queue.remove(payload)
            clear_one(payload)
            continue

        idx = payload
        p = probes[idx]
        unvisited.discard(idx)
        # A channel with two bearings is already localized; do not spend a
        # third measurement on it. Single-bearing channels are deliberately
        # measured first so the selected station serves as their second view.
        order = sorted(active, key=lambda ch: (len(state[ch]['obs']) >= 2,
                                                len(state[ch]['obs'])))
        for ch in order:
            st = state[ch]
            if len(st['obs']) >= 2 or idx in st['tested']:
                continue
            ans = sim.measure(p, ch)
            st['tested'].add(idx)
            result = ans.get('measure_result')
            if result == 'direction':
                st['status'] = '有方向'
                st['obs'].append(Observation(p[0], p[1], ch, result,
                                             float(ans['svd_deg']),
                                             ans.get('virtual_time_s', 0)))
            elif result == 'near':
                st['status'] = '已定位'
                if not any(item[0] == ch for item in clear_queue):
                    clear_queue.append((ch, p, len(st['obs'])))
            elif not st['obs']:
                st['status'] = '无信号'
        enqueue_estimates()

    return state

def run_q3_stable(sim):
    """Stable q3 policy used after rolling back experimental scheduling."""
    probes = q3_probe_points()
    unvisited = set(range(len(probes)))
    state = {ch: {'status': '未发现', 'obs': [], 'estimate': None,
                  'queued_obs_count': -1, 'blocked_obs_count': -1,
                  'no_signal_probes': set(), 'tested_points': set()}
             for ch in range(1, 21)}
    active = set(state)
    clear_queue = []
    coverage_cache = {}

    def redundant_probe(idx, no_signal_probes):
        """Whether this probe's possible source area was already checked."""
        key = (idx, tuple(sorted(no_signal_probes)))
        cached = coverage_cache.get(key)
        if cached is not None:
            return cached
        prior = [probes[i] for i in no_signal_probes if i != idx]
        covered = disk_covered_by_union(probes[idx], prior)
        coverage_cache[key] = covered
        return covered

    def enqueue_estimates():
        for ch in list(active):
            st = state[ch]
            if st['status'] != '有方向' or len(st['obs']) < 2:
                continue
            if len(st['obs']) <= st['blocked_obs_count']:
                continue
            loc = robust_location(st['obs'][-10:])
            if loc is None or math.hypot(*loc) > R + 20:
                continue
            loc = refine_location(st['obs'][-10:], loc)
            st['estimate'] = loc
            st['status'] = '已定位'
            if st['queued_obs_count'] < len(st['obs']):
                clear_queue.append((ch, loc, len(st['obs'])))
                st['queued_obs_count'] = len(st['obs'])

    def clear_nearest():
        if not clear_queue:
            return False
        clear_queue.sort(key=lambda item: math.hypot(item[1][0] - sim.pos[0],
                                                      item[1][1] - sim.pos[1]))
        ch, loc, obs_count = clear_queue.pop(0)
        if ch not in active:
            return False
        if clear_neighborhood(sim, loc, ch):
            state[ch]['status'] = '已清除'
            active.remove(ch)
            return True
        state[ch]['status'] = '有方向'
        state[ch]['estimate'] = None
        state[ch]['blocked_obs_count'] = obs_count
        # The old observations led to a failed clear.  Allow the recovery
        # phase to obtain a genuinely new bearing instead of reusing the same
        # station set forever.
        state[ch]['tested_points'].clear()
        return False

    def recovery_probe(ch):
        """Choose a new station for a channel still marked 有方向."""
        st = state[ch]
        candidates = []
        for idx, p in enumerate(probes):
            if idx in st['tested_points']:
                continue
            if st['obs']:
                # A transverse baseline makes the next ray useful for
                # localization; distance is a secondary tie breaker.
                qualities = []
                for o in st['obs'][-3:]:
                    baseline = math.degrees(math.atan2(p[1] - o.y,
                                                        p[0] - o.x))
                    diff = abs((baseline - o.bearing + 180.0) % 360.0 - 180.0)
                    qualities.append(abs(math.sin(diff * DEG)))
                quality = max(qualities)
            else:
                quality = 0.0
            distance = math.hypot(p[0] - sim.pos[0], p[1] - sim.pos[1])
            candidates.append((-quality, distance, idx))
        if not candidates:
            return None
        return min(candidates)[2]

    def recover_directional(max_actions=260):
        """Finish queued fixes before returning a state to the caller."""
        exhausted = set()
        for _ in range(max_actions):
            enqueue_estimates()
            if clear_queue:
                queued_channels = {item[0] for item in clear_queue}
                clear_nearest()
                for ch in queued_channels:
                    if state[ch]['status'] == '有方向':
                        exhausted.discard(ch)
                continue
            pending = [ch for ch in sorted(active)
                       if state[ch]['status'] == '有方向'
                       and ch not in exhausted]
            if not pending:
                return
            ch = min(pending, key=lambda c: len(state[c]['obs']))
            idx = recovery_probe(ch)
            if idx is None:
                exhausted.add(ch)
                continue
            p = probes[idx]
            st = state[ch]
            ans = sim.measure(p, ch)
            st['tested_points'].add(idx)
            result = ans.get('measure_result')
            if result == 'direction':
                st['obs'].append(Observation(p[0], p[1], ch, result,
                                             float(ans['svd_deg']),
                                             ans.get('virtual_time_s', 0)))
            elif result == 'near':
                st['status'] = '已定位'
                clear_queue.append((ch, p, len(st['obs'])))
            # A no_signal result leaves the channel pending.  The next
            # recovery action uses another station.
        enqueue_estimates()
        while clear_queue:
            clear_nearest()

    # At most 16 channels contain jammers. Once 16 have been cleared, all
    # remaining channels are guaranteed noise and no further measurements are
    # useful.
    while (unvisited or clear_queue) and len(active) > 4:
        enqueue_estimates()
        if clear_queue:
            clear_nearest()
            continue
        if not unvisited:
            break
        idx = min(unvisited, key=lambda i: math.hypot(probes[i][0] - sim.pos[0],
                                                       probes[i][1] - sim.pos[1]))
        p = probes[idx]
        unvisited.remove(idx)
        for ch in sorted(active):
            st = state[ch]
            # A no-signal result only rules out the part of the arena covered
            # by that detector. Skip this channel here only when the complete
            # current probe disk is already covered by those earlier regions.
            if (st['status'] == '无信号'
                    and redundant_probe(idx, st['no_signal_probes'])):
                st['tested_points'].add(idx)
                continue
            ans = sim.measure(p, ch)
            result = ans.get('measure_result')
            st['tested_points'].add(idx)
            if result == 'direction':
                st['status'] = '有方向'
                st['obs'].append(Observation(p[0], p[1], ch, result,
                                             float(ans['svd_deg']),
                                             ans.get('virtual_time_s', 0)))
            elif result == 'near':
                st['status'] = '已定位'
                clear_queue.append((ch, p, len(st['obs'])))
            elif result == 'no_signal':
                st['no_signal_probes'].add(idx)
                if st['status'] == '未发现':
                    st['status'] = '无信号'
        enqueue_estimates()
    recover_directional()
    return state


def run_q4_dynamic(sim):
    """Dynamic q4 search for omnidirectional and 180-degree sources."""
    probes = q4_scan_points()
    state = {ch: {'status': '未发现', 'obs': [], 'tested': set(),
                  'no_signal': set(), 'estimate': None,
                  'failed_obs_count': -1}
             for ch in range(1, 21)}
    active = set(state)
    unvisited = set(range(len(probes)))
    pending_second = set()
    clear_queue = []
    exhausted = set()
    actions = 0
    max_actions = 500

    def key(p):
        return (round(p[0], 6), round(p[1], 6))

    probe_keys = [key(p) for p in probes]
    probe_index = {k: i for i, k in enumerate(probe_keys)}

    def second_candidates(ch):
        st = state[ch]
        result = [p for p in probes if key(p) not in st['tested']]
        # Add side-looking viewpoints derived from the measured rays.  These
        # points are useful when a directional source is visible from only one
        # of the fixed stations, because the next view can stay within the
        # 1000 m receive disk while changing the baseline substantially.
        for o in st['obs'][-3:]:
            a = o.bearing * DEG
            for length in (300.0, 600.0, 900.0, 1200.0):
                for side in (-1.0, 1.0):
                    q = (o.x - side * length * math.sin(a),
                         o.y + side * length * math.cos(a))
                    if math.hypot(*q) <= R and key(q) not in st['tested']:
                        result.append(q)
            # A compact local ring is robust to a noisy first bearing.
            for radius in (400.0, 800.0):
                for k in range(8):
                    t = 2.0 * math.pi * k / 8.0
                    q = (o.x + radius * math.cos(t),
                         o.y + radius * math.sin(t))
                    if math.hypot(*q) <= R and key(q) not in st['tested']:
                        result.append(q)
        # Remove duplicate generated points while preserving order.
        unique = []
        seen = set()
        for p in result:
            k = key(p)
            if k not in seen:
                seen.add(k); unique.append(p)
        return unique

    def enqueue_estimates():
        for ch in list(active):
            st = state[ch]
            if st['status'] != '有方向' or len(st['obs']) < 2:
                continue
            if len(st['obs']) <= st['failed_obs_count']:
                continue
            loc = robust_location(st['obs'][-10:])
            if loc is None or math.hypot(*loc) > R + 20:
                continue
            st['estimate'] = refine_location(st['obs'][-10:], loc)
            st['status'] = '已定位'
            if not any(item[0] == ch for item in clear_queue):
                clear_queue.append((ch, st['estimate'], len(st['obs'])))

    def execute_clear(item):
        ch, loc, obs_count = item
        if ch not in active:
            return
        if clear_neighborhood(sim, loc, ch):
            state[ch]['status'] = '已清除'
            active.remove(ch)
            pending_second.discard(ch)
            exhausted.discard(ch)
            return
        st = state[ch]
        st['status'] = '有方向'
        st['estimate'] = None
        st['failed_obs_count'] = obs_count
        st['tested'].clear()
        pending_second.add(ch)

    def choose_second(ch):
        st = state[ch]
        qs = second_candidates(ch)
        if not qs:
            return None
        observations = st['obs'][-3:]
        def score(p):
            quality = 0.0
            for o in observations:
                baseline = math.degrees(math.atan2(p[1] - o.y, p[0] - o.x))
                delta = abs((baseline - o.bearing + 180.0) % 360.0 - 180.0)
                quality = max(quality, abs(math.sin(delta * DEG)))
            distance = math.hypot(p[0] - sim.pos[0], p[1] - sim.pos[1])
            return distance / 5.0 - 18.0 * quality
        return min(qs, key=score)

    def measure_one(ch, p):
        st = state[ch]
        ans = sim.measure(p, ch)
        st['tested'].add(key(p))
        result = ans.get('measure_result')
        if result == 'direction':
            st['status'] = '有方向'
            st['obs'].append(Observation(p[0], p[1], ch, result,
                                         float(ans['svd_deg']),
                                         ans.get('virtual_time_s', 0)))
            pending_second.add(ch)
        elif result == 'near':
            st['status'] = '已定位'
            pending_second.discard(ch)
            clear_queue.append((ch, p, len(st['obs'])))
        elif not st['obs']:
            st['status'] = '无信号'
            st['no_signal'].add(key(p))
            # A three-point convex-hull certificate is the only safe way to
            # conclude that a directional channel has no source.
            indices = {probe_index[k] for k in st['no_signal']
                       if k in probe_index}
            if q4_three_cover_certified(indices):
                st['certified_absent'] = True

    def finish_directional(limit=180):
        for _ in range(limit):
            enqueue_estimates()
            if clear_queue:
                item = min(clear_queue,
                           key=lambda x: math.hypot(x[1][0] - sim.pos[0],
                                                    x[1][1] - sim.pos[1]))
                clear_queue.remove(item)
                execute_clear(item)
                continue
            pending = [ch for ch in sorted(active)
                       if state[ch]['status'] == '有方向']
            pending = [ch for ch in pending if ch not in exhausted]
            if not pending:
                return
            ch = min(pending, key=lambda c: len(state[c]['obs']))
            p = choose_second(ch)
            if p is None:
                exhausted.add(ch)
                pending_second.discard(ch)
                continue
            measure_one(ch, p)
        enqueue_estimates()
        while clear_queue:
            execute_clear(clear_queue.pop(0))

    while actions < max_actions and len(active) > 4:
        enqueue_estimates()
        if clear_queue:
            item = min(clear_queue,
                       key=lambda x: math.hypot(x[1][0] - sim.pos[0],
                                               x[1][1] - sim.pos[1]))
            clear_queue.remove(item)
            execute_clear(item)
            continue

        candidates = []
        # A second view has more value than starting another blind sweep.
        for ch in sorted(pending_second):
            if ch not in active or ch in exhausted:
                continue
            p = choose_second(ch)
            if p is None:
                exhausted.add(ch)
                continue
            d = math.hypot(p[0] - sim.pos[0], p[1] - sim.pos[1])
            candidates.append((d / 5.0 - 12.0, 'second', (ch, p)))
        if unvisited:
            need = sum(not state[ch]['obs'] for ch in active)
            for idx in unvisited:
                p = probes[idx]
                d = math.hypot(p[0] - sim.pos[0], p[1] - sim.pos[1])
                gain = 0.0
                for ch in active:
                    st = state[ch]
                    if len(st['obs']) >= 2:
                        continue
                    if not st['obs']:
                        gain += 1.0
                        continue
                    o = st['obs'][-1]
                    baseline = math.degrees(math.atan2(p[1] - o.y,
                                                        p[0] - o.x))
                    delta = abs((baseline - o.bearing + 180.0) % 360.0 - 180.0)
                    gain += 0.5 + abs(math.sin(delta * DEG))
                candidates.append((d / 5.0 + 4.0 * max(1, need) - 5.0 * gain,
                                   'discover', idx))
        if not candidates:
            break
        _, kind, payload = min(candidates, key=lambda x: x[0])
        actions += 1
        if kind == 'second':
            ch, p = payload
            measure_one(ch, p)
            continue
        idx = payload
        p = probes[idx]
        unvisited.remove(idx)
        for ch in sorted(active):
            st = state[ch]
            if st.get('certified_absent'):
                continue
            # Once a bearing is available, this channel is handled by the
            # global second-view queue; do not rescan it at every discovery
            # station.
            if st['obs'] or key(p) in st['tested']:
                continue
            measure_one(ch, p)

    finish_directional()
    # One final queue drain catches a valid intersection created by the last
    # measurement in the recovery pass.
    enqueue_estimates()
    while clear_queue:
        execute_clear(clear_queue.pop(0))
    return state

def run(robot_id, base, mode, log_file):
    sim = Simulator(base, robot_id, log_file)
    sim.enter()
    if mode == 'q3':
        state = run_q3_stable(sim)
        sim.exit(); sim.log.close()
        cleared = sorted(ch for ch, st in state.items() if st['status'] == '已清除')
        print(json.dumps({'cleared_channels': cleared, 'count': len(cleared),
                          'states': {str(ch): st['status'] for ch, st in state.items()}},
                         ensure_ascii=False))
        return
    if mode == 'q4':
        state = run_q4_dynamic(sim)
        sim.exit(); sim.log.close()
        cleared = sorted(ch for ch, st in state.items() if st['status'] == '已清除')
        print(json.dumps({'cleared_channels': cleared, 'count': len(cleared),
                          'states': {str(ch): st['status'] for ch, st in state.items()}},
                         ensure_ascii=False))
        return
    pending = {c: [] for c in range(1, 21)}
    cleared = set()
    clear_attempts = {c: 0 for c in range(1, 21)}
    no_signal = {c: 0 for c in range(1, 21)}
    # A 900 m lattice keeps the number of 5-second measurements within the
    # 20-minute run limit while still overlapping the 1000--1500 m receive
    # radii.  Q4 gets a denser lattice because directional sectors can hide
    # a source from a single pass.
    step = 900 if mode == 'q3' else 800
    points = grid_points(step) if mode == 'q3' else q4_scan_points()
    planned = set(points)
    for p in points:
        for ch in range(1, 21):
            if ch in cleared: continue
            ans = sim.measure(p, ch)
            result = ans.get('measure_result')
            if result == 'near':
                if clear_neighborhood(sim, p, ch):
                    cleared.add(ch)
                continue
            if result != 'direction':
                no_signal[ch] += 1
                continue
            b = float(ans['svd_deg'])
            pending[ch].append(Observation(p[0], p[1], ch, result, b, ans.get('virtual_time_s', 0)))
            # Question 2: after the first bearing, schedule a side-looking
            # viewpoint so the next ray intersects close to 90 degrees.
            # This is much more informative than waiting for the next grid
            # point, and is especially important for Q3's omni sources.
            if mode == 'q3' and len(pending[ch]) == 1 and len(planned) < len(grid_points(step)) + 6:
                a = b * DEG
                for side in (-1.0, 1.0):
                    q = (p[0] - side * 750.0 * math.sin(a),
                         p[1] + side * 750.0 * math.cos(a))
                    if math.hypot(*q) <= R and q not in planned:
                        points.append(q); planned.add(q)
                        break
            if len(pending[ch]) >= 2:
                # All past bearings improve conditioning; cap memory so a
                # stale outlier cannot dominate a long run.
                loc = robust_location(pending[ch][-10:])
                if loc is not None and math.hypot(*loc) <= R + 20 and (len(pending[ch]) == 2 or len(pending[ch]) % 3 == 0):
                    loc = refine_location(pending[ch][-10:], loc)
                    clear_attempts[ch] += 1
                    if clear_neighborhood(sim, loc, ch):
                        cleared.add(ch)
            # In Q4 a channel that has only no-signal observations is retained;
            # later viewpoints may enter its 180-degree radiation sector.
        # The problem guarantees at most 16 jammers, so every remaining
        # channel is noise once all 16 have been cleared.
        if len(cleared) >= 16:
            break
    sim.exit(); sim.log.close()
    print(json.dumps({'cleared_channels': sorted(cleared), 'count': len(cleared)}, ensure_ascii=False))

if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--robot-id', required=True)
    ap.add_argument('--base', default='http://127.0.0.1:2026')
    ap.add_argument('--mode', choices=['q4'], default='q4')
    ap.add_argument('--log', default='robot_log.jsonl')
    a = ap.parse_args()
    run(a.robot_id, a.base, a.mode, a.log)
